#!/usr/bin/env bash
# Opt-in Icom IC-705 support: writes udev rules and /opt/vara/bin/start-rigctld-ic705.sh from
# embedded content (no separate repo templates), dialout group, and profile INIs under
# /opt/vara/profiles/ic-705.
#
# Default (sudo): system setup + INI generation as VARA_USER.
#   sudo ./setup-ic705.sh
# System only (no INIs):
#   sudo ./setup-ic705.sh --system-only
# INIs only (as ham, no root):
#   ./setup-ic705.sh --ini-only
#
# Then: sudo ./install-varanny.sh  (adds IC705FM / IC705HF with CatCtrl to varanny.json)

set -euo pipefail

readonly VARA_ROOT="${VARA_ROOT:-/opt/vara}"
readonly VARA_USER="${VARA_USER:-ham}"
readonly PROFILE_SUBDIR_IC705="profiles/ic-705"
readonly UDEV_RULES_DST=/etc/udev/rules.d/99-ic-705.rules
readonly RIGCTLD_HELPER_DST="${VARA_ROOT}/bin/start-rigctld-ic705.sh"

die() {
  echo "error: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage:
  sudo ./setup-ic705.sh              Install udev rules, rigctld helper, dialout; write profile INIs
  sudo ./setup-ic705.sh --system-only  Udev + /opt/vara/bin/start-rigctld-ic705.sh + dialout only
       ./setup-ic705.sh --ini-only     Write /opt/vara/profiles/ic-705/*.ini as current user (no root)

Environment:
  VARA_ROOT   default /opt/vara
  VARA_USER   default ham (for dialout; sudo run re-invokes --ini-only as this user)

INI automation: VARA_CALLSIGN and VARA_REGISTRATION_CODE (both); when set, prompts are skipped even in a terminal.

Next: sudo ./install-varanny.sh
USAGE
}

validate_fields() {
  local callsign=$1 reg=$2
  [[ -n "$callsign" ]] || die "callsign is empty"
  [[ -n "$reg" ]] || die "registration code is empty"
  [[ "$callsign" != *$'\n'* && "$reg" != *$'\n'* ]] || die "values must not contain newlines"
  [[ "$callsign" != *=* ]] || die "callsign must not contain '='"
  [[ "$reg" != *=* ]] || die "registration code must not contain '='"
}

collect_inputs() {
  if [[ -n "${VARA_CALLSIGN:-}" ]] && [[ -n "${VARA_REGISTRATION_CODE:-}" ]]; then
    CALLSIGN=$VARA_CALLSIGN
    REGISTRATION_CODE=$VARA_REGISTRATION_CODE
    validate_fields "$CALLSIGN" "$REGISTRATION_CODE"
    return
  fi
  if [[ ! -t 0 ]]; then
    die "stdin is not a terminal; set both VARA_CALLSIGN and VARA_REGISTRATION_CODE"
  fi

  local line
  read -rp "Callsign: " line || die "read failed"
  CALLSIGN=$(printf '%s' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  read -rsp "VARA registration code (hidden): " REGISTRATION_CODE || die "read failed"
  echo
  validate_fields "$CALLSIGN" "$REGISTRATION_CODE"
}

write_vara_ini() {
  local out=$1
  cat >"$out" <<INI
[Soundcard]
Input Device Name=In: USB Audio CODEC - USB Audio
Output Device Name=Out: USB Audio CODEC - USB Audi
ALC Drive Level=-5
Channel=0
[Setup]
Registration Code=${REGISTRATION_CODE}
Callsign Licence 0=${CALLSIGN}
WaterFall=0
TCP Command Port=8300
Retries=20
View=3
CW ID=0
RA-Board PTT=0
Compatibility=0
Updates=0
ATU=0
Encryption=0
Persistence=0.4
Enable KISS=0
KISS Port=8100
[Monitor]
Monitor Mode=0
INI
}

write_varafm_ini() {
  local out=$1
  cat >"$out" <<INI
[Soundcard]
Input Device Name=In: USB Audio CODEC - USB Audio
Output Device Name=Out: USB Audio CODEC - USB Audi
ALC Drive Level=-5
Channel=0
[Setup]
Registration Code=${REGISTRATION_CODE}
Callsign Licence 0=${CALLSIGN}
Updates=0
Enable KISS=0
KISS Port=8100
TCP Command Port=8300
TCP Scan Port=8427
Retries=10
FM Mode=1
View=3
Encryption=0
INI
}

write_profile_inis() {
  local profile_dir=$1
  profile_dir=$(readlink -f "$profile_dir" 2>/dev/null || printf '%s' "$profile_dir")
  collect_inputs
  mkdir -p "$profile_dir"
  local f_vara f_fm
  f_vara="${profile_dir}/vara.ini"
  f_fm="${profile_dir}/varafm.ini"
  write_vara_ini "$f_vara"
  write_varafm_ini "$f_fm"
  chmod 600 "$f_vara" "$f_fm"
  echo
  echo "Wrote (mode 600):"
  echo "  $f_vara"
  echo "  $f_fm"
}

# Written to $UDEV_RULES_DST — verify ATTRS{product} with: udevadm info -a -n /dev/ttyACM0
write_udev_rules_ic705() {
  local dst=$1
  cat >"$dst" <<'RULES'
# Icom IC-705: stable /dev symlinks for CAT (ic-705a) and audio (ic-705b).
# Generated by setup-ic705.sh — edit here on the target if ATTRS{product} differs.

KERNEL=="ttyACM[0-9]*", SUBSYSTEM=="tty", ATTRS{product}=="IC-705", ENV{PROD}="IC-705"
ENV{PROD}=="IC-705", SUBSYSTEMS=="usb", ATTRS{bInterfaceNumber}=="00", SYMLINK+="ic-705a"
ENV{PROD}=="IC-705", SUBSYSTEMS=="usb", ATTRS{bInterfaceNumber}=="02", SYMLINK+="ic-705b"
RULES
  chmod 0644 "$dst"
}

# Installed as $RIGCTLD_HELPER_DST — same body as install-varanny.sh (keep in sync).
write_rigctld_helper_ic705() {
  local dst=$1
  cat >"$dst" <<'RIGSCRIPT'
#!/usr/bin/env bash
# Started by varanny CatCtrl (per IC-705 modem). Idempotent: exits 0 if TCP port already in use.
# Override: RIGCTLD_MODEL RIGCTLD_DEVICE RIGCTLD_PORT

set -euo pipefail

MODEL="${RIGCTLD_MODEL:-3085}"
DEVICE="${RIGCTLD_DEVICE:-/dev/ic-705a}"
PORT="${RIGCTLD_PORT:-4532}"

port_listening() {
  command -v ss >/dev/null 2>&1 || return 1
  ss -Hltn "sport = :$PORT" 2>/dev/null | grep -q .
}

if port_listening; then
  exit 0
fi

[[ -e "$DEVICE" ]] || {
  echo "start-rigctld-ic705: missing $DEVICE (plug IC-705 or fix udev); not starting rigctld" >&2
  exit 1
}

exec rigctld -m "$MODEL" -r "$DEVICE" -t "$PORT"
RIGSCRIPT
  chmod 0755 "$dst"
}

install_system_bits() {
  [[ $EUID -eq 0 ]] || die "system setup requires root (sudo ./setup-ic705.sh)"

  id -u "$VARA_USER" >/dev/null 2>&1 || die "user $VARA_USER does not exist"

  install -d -m 0755 "${VARA_ROOT}/bin"
  write_rigctld_helper_ic705 "$RIGCTLD_HELPER_DST"
  echo "Wrote $RIGCTLD_HELPER_DST"

  write_udev_rules_ic705 "$UDEV_RULES_DST"
  echo "Wrote $UDEV_RULES_DST"

  udevadm control --reload-rules
  udevadm trigger
  echo "Reloaded udev rules (replug IC-705 if it was already connected)."

  if id -nG "$VARA_USER" | tr ' ' '\n' | grep -qx dialout; then
    echo "User $VARA_USER is already in group dialout"
  else
    usermod -aG dialout "$VARA_USER"
    echo "Added $VARA_USER to group dialout (log out and back in, or reboot, for it to apply)."
  fi

  mkdir -p "${VARA_ROOT}/${PROFILE_SUBDIR_IC705}"
  chown "${VARA_USER}:${VARA_USER}" "${VARA_ROOT}/${PROFILE_SUBDIR_IC705}" 2>/dev/null || true
}

main() {
  local system_only=0 ini_only=0
  while [[ $# -gt 0 ]]; do
    case $1 in
      --system-only) system_only=1 ;;
      --ini-only) ini_only=1 ;;
      -h | --help) usage; exit 0 ;;
      *) die "unknown option: $1 (try -h)" ;;
    esac
    shift
  done

  if [[ "$ini_only" -eq 1 ]]; then
    [[ $EUID -ne 0 ]] || die "run --ini-only as $VARA_USER (not root), e.g. ssh ham@…"
    write_profile_inis "${VARA_ROOT}/${PROFILE_SUBDIR_IC705}"
    echo "Next: sudo ./install-varanny.sh"
    exit 0
  fi

  [[ $EUID -eq 0 ]] || die "run with sudo, or use ./setup-ic705.sh --ini-only as $VARA_USER"

  install_system_bits

  if [[ "$system_only" -eq 1 ]]; then
    echo "Skipping INIs (--system-only). Run ./setup-ic705.sh --ini-only as $VARA_USER, or sudo ./setup-ic705.sh without --system-only."
    exit 0
  fi

  self=$(readlink -f "${BASH_SOURCE[0]}")
  echo
  echo "Writing profile INIs as $VARA_USER (re-invoking $self --ini-only)..."
  sudo -u "$VARA_USER" env VARA_ROOT="$VARA_ROOT" VARA_CALLSIGN="${VARA_CALLSIGN:-}" VARA_REGISTRATION_CODE="${VARA_REGISTRATION_CODE:-}" "$self" --ini-only

  echo
  echo "Done. Next: sudo ./install-varanny.sh"
}

main "$@"
