#!/usr/bin/env bash
# Configure hostapd + dnsmasq as a Wi-Fi access point on Debian (static IP on the AP interface).
# Wireless interface: auto-detected (ip / iw / sysfs) unless -i or WIFI_AP_IFACE is set.
# Subnet default 192.168.50.0/24.
#
# Run with sudo. Install packages first if needed: apt install hostapd dnsmasq
#
# Stop/disable NetworkManager (or unmanage this interface) if it conflicts with hostapd.

set -euo pipefail

readonly DEFAULT_SSID="${WIFI_AP_SSID:-VARA-Modem}"
readonly DEFAULT_PSK="${WIFI_AP_PSK:-varamodem}"
readonly DEFAULT_CHANNEL="${WIFI_AP_CHANNEL:-6}"
readonly AP_ADDRESS="${WIFI_AP_ADDRESS:-192.168.50.1}"
readonly AP_NETMASK="${WIFI_AP_NETMASK:-255.255.255.0}"
readonly DHCP_START="${WIFI_AP_DHCP_START:-192.168.50.100}"
readonly DHCP_END="${WIFI_AP_DHCP_END:-192.168.50.150}"
readonly DHCP_LEASE_H="${WIFI_AP_DHCP_LEASE:-12h}"
readonly COUNTRY="${WIFI_AP_COUNTRY:-US}"
# CIDR prefix for static AP address (used with ip(8) before dnsmasq starts)
readonly AP_PREFIX="${WIFI_AP_PREFIX:-24}"

readonly HOSTAPD_CONF=/etc/hostapd/hostapd.conf
readonly DNSMASQ_SNIPPET=/etc/dnsmasq.d/vara-ap.conf
readonly INTERFACES_SNIPPET=/etc/network/interfaces.d/50-vara-ap.conf
readonly HOSTAPD_DEFAULT=/etc/default/hostapd

die() {
  echo "error: $*" >&2
  exit 1
}

usage() {
  cat <<USAGE
Usage: sudo $0 [options]

Writes:
  $HOSTAPD_CONF
  $DNSMASQ_SNIPPET
  $INTERFACES_SNIPPET
and sets DAEMON_CONF in $HOSTAPD_DEFAULT. Enables hostapd + dnsmasq.

Options:
  -i IFACE   Wireless interface (skip auto-detection; required if several wlan devices exist)
  -s SSID    SSID (default: VARA-Modem or \$WIFI_AP_SSID)
  -p PSK     WPA2 passphrase (default: from \$WIFI_AP_PSK)
  --install-deps  apt install hostapd dnsmasq (noninteractive)
  --no-start      Do not restart services (only write configs + enable)

Environment (optional): WIFI_AP_IFACE (forces interface; skips detection)
  WIFI_AP_SSID WIFI_AP_PSK WIFI_AP_CHANNEL
  WIFI_AP_ADDRESS WIFI_AP_NETMASK WIFI_AP_PREFIX (CIDR bits, default 24)
  WIFI_AP_DHCP_START WIFI_AP_DHCP_END WIFI_AP_DHCP_LEASE WIFI_AP_COUNTRY (ISO 3166-1 alpha-2)

The script brings up IFACE and assigns the static IP before restarting dnsmasq (dnsmasq
otherwise fails with "unknown interface" if the wlan has no address yet). Uses bind-dynamic
instead of bind-interfaces for safer startup ordering.
USAGE
}

require_root() {
  [[ $EUID -eq 0 ]] || die "run as root (sudo)"
}

backup_if_exists() {
  local f=$1
  [[ -f "$f" ]] || return 0
  cp -a "$f" "${f}.bak.$(date +%Y%m%d%H%M%S)"
  echo "Backed up $f"
}

install_deps() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y hostapd dnsmasq
}

ensure_packages() {
  command -v hostapd >/dev/null 2>&1 || die "install hostapd: apt install hostapd (or run with --install-deps)"
  command -v dnsmasq >/dev/null 2>&1 || die "install dnsmasq: apt install dnsmasq (or run with --install-deps)"
}

# Pick the sole wireless interface, or fail if none / ambiguous.
detect_wifi_interface() {
  local -a candidates=()
  local ifc w

  if command -v ip >/dev/null 2>&1; then
    mapfile -t candidates < <(ip -brief link show type wifi 2>/dev/null | awk 'NF { print $1 }')
    if [[ ${#candidates[@]} -eq 1 ]]; then
      printf '%s\n' "${candidates[0]}"
      return 0
    fi
    if [[ ${#candidates[@]} -gt 1 ]]; then
      echo "error: multiple wireless interfaces: ${candidates[*]}" >&2
      echo "error: choose one: sudo $0 -i <iface>   or   export WIFI_AP_IFACE=<iface>" >&2
      return 1
    fi
  fi

  if command -v iw >/dev/null 2>&1; then
    mapfile -t candidates < <(iw dev 2>/dev/null | awk '$1 == "Interface" { print $2 }')
    if [[ ${#candidates[@]} -eq 1 ]]; then
      printf '%s\n' "${candidates[0]}"
      return 0
    fi
    if [[ ${#candidates[@]} -gt 1 ]]; then
      echo "error: multiple wireless interfaces (iw): ${candidates[*]}" >&2
      echo "error: choose one: sudo $0 -i <iface>   or   export WIFI_AP_IFACE=<iface>" >&2
      return 1
    fi
  fi

  candidates=()
  for w in /sys/class/net/*/wireless; do
    [[ -e "$w" ]] || continue
    ifc=$(basename "$(dirname "$w")")
    [[ "$ifc" == "lo" ]] && continue
    candidates+=("$ifc")
  done
  if [[ ${#candidates[@]} -eq 1 ]]; then
    printf '%s\n' "${candidates[0]}"
    return 0
  fi
  if [[ ${#candidates[@]} -gt 1 ]]; then
    echo "error: multiple wireless interfaces (sysfs): ${candidates[*]}" >&2
    echo "error: choose one: sudo $0 -i <iface>   or   export WIFI_AP_IFACE=<iface>" >&2
    return 1
  fi

  echo "error: no wireless interface found (try: ip link; install iw; or use -i IFACE)" >&2
  return 1
}

write_hostapd_conf() {
  local iface=$1 ssid=$2 psk=$3 channel=$4
  umask 077
  tee "$HOSTAPD_CONF" >/dev/null <<EOF
# VARA AP — generated by setup-wifi-ap.sh
country_code=${COUNTRY}
interface=${iface}
driver=nl80211
ssid=${ssid}
hw_mode=g
channel=${channel}
wpa=2
wpa_passphrase=${psk}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
EOF
  chmod 600 "$HOSTAPD_CONF"
  umask 022
}

write_dnsmasq_snippet() {
  local iface=$1
  tee "$DNSMASQ_SNIPPET" >/dev/null <<EOF
# VARA AP — generated by setup-wifi-ap.sh
# bind-dynamic: tolerate interface/IP appearing at boot; avoids "unknown interface" if
# dnsmasq starts before the wlan is fully up (bind-interfaces is stricter).
interface=${iface}
bind-dynamic
dhcp-range=${DHCP_START},${DHCP_END},${DHCP_LEASE_H}
EOF
}

write_interfaces_snippet() {
  local iface=$1
  tee "$INTERFACES_SNIPPET" >/dev/null <<EOF
# VARA AP — generated by setup-wifi-ap.sh
auto ${iface}
iface ${iface} inet static
	address ${AP_ADDRESS}
	netmask ${AP_NETMASK}
EOF
}

# Assign static AP IP before dnsmasq starts (dnsmasq needs the netdev + address present).
bring_up_ap_interface() {
  local iface=$1
  local cidr="${AP_ADDRESS}/${AP_PREFIX}"

  ip link set "$iface" up || die "failed: ip link set $iface up (rfkill? nmcli? check: ip link show $iface)"

  if ip -brief addr show "$iface" 2>/dev/null | grep -qE "[[:space:]]${AP_ADDRESS}/"; then
    echo "Interface $iface already has $AP_ADDRESS"
    return 0
  fi

  if command -v ifup >/dev/null 2>&1; then
    if ifup "$iface" 2>/dev/null; then
      echo "Brought up $iface via ifup"
      return 0
    fi
  fi

  ip addr flush dev "$iface" 2>/dev/null || true
  if ip addr add "$cidr" dev "$iface" 2>/dev/null; then
    echo "Assigned $cidr on $iface (ip addr add)"
  elif ip addr replace "$cidr" dev "$iface" 2>/dev/null; then
    echo "Assigned $cidr on $iface (ip addr replace)"
  else
    die "failed to assign $cidr on $iface — check for NetworkManager or conflicting addresses"
  fi
}

ensure_hostapd_default() {
  if [[ -f "$HOSTAPD_DEFAULT" ]]; then
    backup_if_exists "$HOSTAPD_DEFAULT"
    if grep -qE '^#?DAEMON_CONF=' "$HOSTAPD_DEFAULT"; then
      sed -i 's|^#*DAEMON_CONF=.*|DAEMON_CONF="'"$HOSTAPD_CONF"'"|' "$HOSTAPD_DEFAULT"
    else
      echo "DAEMON_CONF=\"$HOSTAPD_CONF\"" >>"$HOSTAPD_DEFAULT"
    fi
  else
    {
      echo "DAEMON_CONF=\"$HOSTAPD_CONF\""
      echo 'DAEMON_OPTS=""'
    } >"$HOSTAPD_DEFAULT"
  fi
  # systemd unit references \$DAEMON_OPTS; empty string avoids "unset variable" warnings.
  if grep -qE '^#?DAEMON_OPTS=' "$HOSTAPD_DEFAULT" 2>/dev/null; then
    sed -i 's|^#*DAEMON_OPTS=.*|DAEMON_OPTS=""|' "$HOSTAPD_DEFAULT"
  else
    echo 'DAEMON_OPTS=""' >>"$HOSTAPD_DEFAULT"
  fi
}

main() {
  local iface="" ssid=$DEFAULT_SSID psk=$DEFAULT_PSK channel=$DEFAULT_CHANNEL
  local no_start=0 install_deps_flag=0 iface_explicit=0

  while [[ $# -gt 0 ]]; do
    case $1 in
      -i)
        [[ -n "${2:-}" ]] || die "-i requires an interface name"
        iface=$2
        iface_explicit=1
        shift 2
        ;;
      -s)
        [[ -n "${2:-}" ]] || die "-s requires an SSID"
        ssid=$2
        shift 2
        ;;
      -p)
        [[ -n "${2:-}" ]] || die "-p requires a passphrase"
        psk=$2
        shift 2
        ;;
      --install-deps) install_deps_flag=1; shift ;;
      --no-start) no_start=1; shift ;;
      -h | --help) usage; exit 0 ;;
      *) die "unknown option: $1 (use -h)" ;;
    esac
  done

  require_root
  [[ "$install_deps_flag" -eq 1 ]] && install_deps
  ensure_packages

  if [[ "$iface_explicit" -eq 1 ]]; then
    [[ -n "$iface" ]] || die "-i requires a non-empty interface name"
  elif [[ -n "${WIFI_AP_IFACE:-}" ]]; then
    iface=$WIFI_AP_IFACE
    echo "Using interface from WIFI_AP_IFACE: $iface"
  else
    iface=$(detect_wifi_interface) || die "could not auto-detect wireless interface"
    echo "Auto-detected wireless interface: $iface"
  fi

  [[ -d "/sys/class/net/$iface" ]] ||
    die "interface '$iface' not found under /sys/class/net (wrong name or driver missing?)"

  backup_if_exists "$HOSTAPD_CONF"

  write_hostapd_conf "$iface" "$ssid" "$psk" "$channel"
  write_dnsmasq_snippet "$iface"
  write_interfaces_snippet "$iface"
  ensure_hostapd_default

  systemctl unmask hostapd.service 2>/dev/null || true
  systemctl enable hostapd.service
  systemctl enable dnsmasq.service

  if [[ "$no_start" -eq 0 ]]; then
    bring_up_ap_interface "$iface"
    systemctl restart dnsmasq.service
    systemctl restart hostapd.service
    systemctl --no-pager --full status dnsmasq.service hostapd.service || true
  fi

  echo
  echo "Configured AP on $iface: SSID=$ssid, AP IP=$AP_ADDRESS, DHCP $DHCP_START–$DHCP_END"
  echo "Configs: $HOSTAPD_CONF, $DNSMASQ_SNIPPET, $INTERFACES_SNIPPET"
  echo "On reboot, if dnsmasq fails again, ensure $iface is up before dnsmasq (interfaces.d + ifup)."
  echo "If hostapd fails, check: rfkill; and that NetworkManager is not managing $iface."
}

main "$@"
